source/config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gan/', include('gan.urls')),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/gan/urls.py

from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name='gan'

urlpatterns = [

    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

source/gan/models.py
from django.db import models
from tensorflow import keras
from tensorflow.keras.models import load_model
from PIL import Image
from gan.network import CycleGAN
from django.conf import settings

import numpy as np
import tensorflow as tf
import io, base64

graph = tf.get_default_graph()


class Photo(models.Model):

    image = models.ImageField(upload_to='images/')


    def predict(self):

        global graph
        
        with graph.as_default():
            cycle_gan = CycleGAN()
            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)
            image = Image.open(img_bin).convert("RGB")
            translated_img = cycle_gan.predict(image)

            return translated_img

source/gan/forms.py
from django import forms
from .models import Photo


class PhotoForm(forms.ModelForm):


    class Meta:
        model = Photo
        fields = ('image',)
    
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class':'custom-file-input'}))

source/gan/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo
from django.http import JsonResponse
import io, base64
from PIL import Image
import numpy as np
import io
import mimetypes


def index(request):
    template = loader.get_template('gan/index.html')
    context = {'form': PhotoForm()}

    return HttpResponse(template.render(context, request))


def predict(request):
    if not request.method == 'POST':
        return redirect('gan:index')
    
    form = PhotoForm(request.POST, request.FILES)
    if not form.is_valid():
        raise ValueError('Formが不正です。')
    
    file_name = form.cleaned_data['image'].name
    print("file_name=", file_name)
    photo = Photo(image=form.cleaned_data['image'])

    
    translated_img = photo.predict() # (1, 128, 128, 3)
    #photo.save()
    translated_img = np.squeeze(translated_img, 0)  # (1, 128, 128, 3) -> (128, 128, 3)
    translated_img = 0.5 * translated_img + 0.5 # 0～1に変換
    pil_img = Image.fromarray((translated_img * 255).astype('uint8'), mode='RGB')
    buffer = io.BytesIO()
    pil_img.save(buffer, format="PNG")
    img_str = base64.b64encode(buffer.getvalue())
    img_str = str(img_str)[2:-1]
    content_type=mimetypes.guess_type(file_name)[0]
    translated_img = 'data:' + content_type + ';base64,' + img_str

    d = {
        'img_str' : translated_img,
    }
    return JsonResponse(d)



    

source/gan/templates/gan/base.html
{% load static %}
<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Demo Apps</title>
<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p:400,500" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/loading_style.css' %}" rel="stylesheet">
</head>
<body>
<header>
<!-- Ajax通信時にloading画面表示 start-->
<div id="overlay">
  <div class="cv-spinner">
    <span class="spinner"></span>
  </div>
</div>
<!-- Ajax通信時にloading画面表示 end -->
<div class="container">
  <h1>CycleGANによる画像のカラー化</h1>
</div><!-- /.container -->
</header>
<main>
<div class="container">
  {% block content %}{% endblock %}
</div>
</section>
</main>
<footer>
<div class="container">
  <p>Django & StyleGAN  </p>
</div><!-- /.contain>er -->
</footer>
</body>
</html>




source/gan/templates/gan/index.html
{% extends 'gan/base.html' %}
{% load static %}
{% block content %}

<section>
  <h1>GrayToColor</h1>
  <p>モノクロ画像をアップロードするとGANモデルによって自動的に画像をカラーに変換します。</p>
  <!-- 画像表示 -->
  <table cellpadding="5">
    <tr>
      <td><img src="{% static 'img/gray.jpg' %}" width="200px" height="200px"></td>
      <td><img src="{% static 'img/color.jpg' %}" width="200px" height="200px"></td>
    </tr>
    <tr>
      <td>モノクロ画像(インプット）</td>
      <td>カラー画像(アウトプット）</td>  
    </tr>
  </table>
</section>  
<section>
<hr>
<h1>画像をアプロード</h1>
<p>モノクロ画像をアップロードするとGANモデルによって自動的に画像をカラーに変換します。</p>
<!-- 画像表示 -->
<table cellpadding="5">
  <tr>
    <td class="box6" ><img id="img1" width="230px" height="230px"></td>
    <td class="box6"><img id="img2" width="230px" height="230px"></td>
  </tr>
  <tr>
    <td>インプット</td>
    <td>アウトプット</td>
   
  </tr>
</table>

<form action="{% url 'gan:predict' %}" method="post" class="form" enctype="multipart/form-data" id="imgForm">
  {% csrf_token %}
  <div class="form-group">
    <div class="custom-file">
      {{ form.image}}
    </div>
  </div>
  <button type="submit" id="button" class="btn">Colorize</button>
</form>
</section>

<script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>

<!-- javascript -->
<script>  
$(function(){
  $('#id_image').change(function(e){
    //ファイルオブジェクトを取得する
    var file = e.target.files[0];
    var reader = new FileReader();
 
    //画像でない場合は処理終了
    if(file.type.indexOf("image") < 0){
      alert("画像ファイルを指定してください。");
      return false;
    }
 
    //アップロードした画像を設定する
    reader.onload = (function(file){
      return function(e){
       
        $("#img1").attr("src", e.target.result);
        $("#img1").attr("title", file.name);
      };
    })(file);
    reader.readAsDataURL(file);
 
  });
});
</script>

<!-- セキュリティ対応-->
<script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    // セキュリティ対応

   // 画像をアップロード
        // 送信ボタンで呼ばれる
        //Ajax通信中にローディングを表示
        $('#imgForm').on('submit', e => {
            // デフォルトのイベントをキャンセルし、ページ遷移しないように!
            e.preventDefault();
            $(document).ajaxSend(function() {
          $("#overlay").fadeIn(300);　
      });
            var formData = new FormData($('#imgForm').get(0));
            $.ajax({
                'url': '{% url "gan:predict" %}',
                'type': 'POST',
                'processData': false,
                'contentType': false,
                'data': formData,
            }).done( response => { 
                console.log("success2!");
                $("#img2").attr("src", response.img_str);
                setTimeout(function(){
                  $("#overlay").fadeOut(300);
              },500);
            })
            .fail((ata, textStatus, xhr) => {
                alert(xhr);
            });
        });
</script>


{% endblock %}